### ISSUE TITLE
Add automatic determination of station timing offset to jobs

### ISSUE THREAD

**Issue by 153957** [HiSPARC/publicdb#133]
Station offsets are needed when reconstructing coincidences, see HiSPARC/sapphire#111
Station offsets change over time, most drastically when swapping GPS antennae, or when moving a station. Other factors may also affect the mean offset. Offsets should be determined often, like detector timing offsets. However, more than a single day of data is needed if the stations are far apart.

- [x] Add new model to store the offsets (see #137)
    - What should be used as Foreign keys?
        - [ ] ~~Two Station objects (with date/time)~~
        - [x] Two Summary objects
        - [ ] ~~A NetworkSummary and two Stations..~~
- [x] Collect coincidence between pairs of stations of period of time (depending on distance)
    - [x] Look for configuration (electronics and GPS) changes in the stations to possible use as boundaries between the periods.
    - [x]  Determine and store the offsets.
    - [x] Add accuracy of the offset, this can be used to determine if direct offsets are used, or offsets via another station.
- [x] Determine and store time difference between coincident events for station pairs (#136)
- [x] Implement Source TSV urls between pairs of stations to retrieve the determined station offsets, see HISPARC/sapphire#110
    - [x] Only allow sorted station numbers, i.e. `.../501/502/`, not `.../502/501/`.
- [x] Implement generating Source TSV
- [x] Set offsets for days of transitions (electronics/GPS) to nan (None in the database)

**Comment by 153957** [comment]
Discussed with @tomkooij:

- Determine time delta between station pairs daily, based on determined coincidences and using the determined detector offsets.
- Store these in the ESD data in some new group, e.g. `time_delta/[ref_station]/[station]`
- Add `c_id` and `delta` columns (possibly also `timestamp`), where `c_id` refers back to the coincidence id from which the events are.
- Then determine the station offsets for station pairs.
- Use periods bound by configuration changes (mainly GPS location or electronics switch), chop these into smaller pieces, as allowed by the distance between the stations.


Later thought:
- Be careful when determining time deltas from coincidences, some coincidences might contain the same subset of events, (as long as the total coincidence is not a subset of an other). Since we will be using subsets of coincidences this might cause problems.

**Comment by 153957** [comment]
For the first run I disabled processing of the dates around the date of the network summary being processed.
I am not certain if this may have allowed dates upon which a config transition occurs are included, that needs to be checked.

**Comment by tomkooij** [comment]
We should make sure ```sapphire.analysis.calibration.DetermineStationTimingOffsets``` set the days with config transitions to nan,nan. (with tests). 

But also in the publicdb jobs: The current algorithm leaves the offset of the transition day as is.

A station could already have a stationtimingoffset on a certain day because it sent some data just before an electronics change. The configuration change may be recieved the next day, or much later. The offsets of the day with the transition needs to be reset to nan,nan when recalculating station timing offsets.

**Comment by 153957** [comment]
Setting days of cuts to nan should be fixed by https://github.com/HiSPARC/sapphire/commit/245af53242b2ce2375381b260e75f76cc4d7be97

**Comment by 153957** [comment]
Implemented, seems to work fine. May be improved later by fine tuning the fitting and the number of days used depending on distances.
